### ISSUE TITLE
Completar registro de 100 personas en el formulario mailchimp y enviar boletín

### ISSUE THREAD

**Issue by danilonunezgil** [danilonunezgil/Restaurante-La-Casa#18]

**Comment by edgarlozadagonzalez** [comment]
Se realizó el registro de las 100 personas.



![Image](https://user-images.githubusercontent.com/110056560/186531814-7cd380ac-665a-4ee0-ac4d-d2757884c7c2.png)


De igual manera se realizó el diseño del correo a enviar cada persona.



![Image](https://user-images.githubusercontent.com/110056560/186531998-e37acb1e-8999-4dec-be7d-0e54b4adda37.png)
